### ISSUE TITLE
SyntaxError: Unexpected token ... at  Line 428 of fhir-kit-client/lib/client.js

### ISSUE THREAD

**Issue by cravelight** [Vermonster/fhir-kit-client#103]
## Expected Behavior
A project with this dependency should run in node.

## Actual Behavior
`SyntaxError: Unexpected token ...` when starting in node

## Steps to Reproduce the Problem

  1. include the latest version of the library
  1. start node

## Notes

I think it's an accidental typo from 439ff3b.  Line 428 of `fhir-kit-client/lib/client.js` reads 
```
const requestHeaders = { ...customHeaders, 'Content-Type': 'application/json-patch+json' };
```
should read
```
const requestHeaders = { customHeaders, 'Content-Type': 'application/json-patch+json' };
```

**Comment by Jammjammjamm** [comment]
That code is as intended. Are you using an older version of node?

**Comment by cravelight** [comment]
older but not ancient - 8.1.2
