### ISSUE TITLE
queryUrlToString()

### ISSUE THREAD

**Issue by awatson1978** [Vermonster/fhir-kit-client#123]
## Feature Request

This is a feature request for a `queryToString()` function, to assist in debugging more complex queries.

## Code Example

Take this example, where we are trying to create a more complex query of COVID19 related conditions within a specified time range.  

```js
import Client from 'fhir-kit-client';

let fhirClient = new Client({
  baseUrl: 'http://localhost:3100/baseR4' 
});

let searchOptions = { 
  resourceType: 'Condition',
  code: "49727002,267036007,386661006",
  searchParams: {} 
};

let selectedStartDate = "2020-03-01";
let selectedEndDate = "2020-03-31";
    
searchOptions.searchParams["onset-date"] = [];
searchOptions.searchParams["onset-date"][0] = "ge" + selectedStartDate;
searchOptions.searchParams["onset-date"][1] = "le" +  selectedEndDate;

// we can debug somewhat, but inspecting the search options that are fed into the fhirClient
console.log('searchOptions', searchOptions)

// but it would be very beneficial to be able to inspect the string that is generated directly
await fhirClient.search(searchOptions).queryUrlToString()

// http://localhost:3100/baseR4/Condition?code=49727002,267036007,386661006&onset-date=ge2020-03-01&onset-date=ge2020-03-31
```

**Comment by bkaney** [comment]
Did you try `DEBUG=fhir-kit-client:*` when running your code? Is that what you were thinking?

**Comment by awatson1978** [comment]
Ah, I suppose I could read the docs a bit more closely.  Will try that, and see how it works.  But that wouldn't necessarily let us expose it to the UI.  Better than nothing, I suppose.

**Comment by bkaney** [comment]
Okay. We could see how to expose the logger a bit nicer if that makes sense. Let me know.

**Comment by bkaney** [comment]
Ah, I forgot you can also get at the request object directly, which should have the query string. See https://vermonster.github.io/fhir-kit-client/fhir-kit-client/1.4.2/module-fhir-kit-client-Client.html#.httpFor

**Comment by awatson1978** [comment]
That certainly helps after the fact.  Not doesn't help for debugging.  Is it available in the `catch()`?  If so, that would cover all the needs.

**Comment by bkaney** [comment]
In the catch, this the error object:
```
  const error = {
    response: {
      status,
      data
    },
    config: {
      method,
      url,
      headers
    }
  };
```

So this will give you the requested method, headers and url:
```
fhirClient.read(...)
   .then(...)
   .catch(error => console.dir(error.config))
```
