### ISSUE TITLE
abort-controller issue after upgrade to Angular 12 

### ISSUE THREAD

**Issue by polaroffer** [Vermonster/fhir-kit-client#147]
## Expected Behavior
ng build without issue

## Actual Behavior

./node_modules/abort-controller/polyfill.mjs:2:0-46 - Error: Module not found: Error: Can't resolve './dist/abort-controller' in 'C:\UserData\ang12\flex-form-ui\node_modules\abort-controller'   
Did you mean 'abort-controller.mjs'?
BREAKING CHANGE: The request './dist/abort-controller' failed to resolve only because it was resolved as fully specified
(probably because the origin is a '*.mjs' file or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

## Steps to Reproduce the Problem

  1.  angular 12 project with fhir-kit-client example
  2.  npm i fhir-kit-client
  3. ng build 

## Specifications

  - Version:  nodejs 14.16  + angular 12 + fhir-kit-client@latest 
  - Platform: windows
  - Subsystem:

**Comment by bkaney** [comment]
Is this still a problem? I don't have windows and can't reproduce.
