### ISSUE TITLE
Question: Is there a way to make a search not be `exact`

### ISSUE THREAD

**Issue by floofydoug** [Vermonster/fhir-kit-client#150]
Search method `:contains`. 

Does a simple patient search for `wash` return results for a name like `washington`? 

Is there a way to make a search not be `exact` like this `contains` modifier? 
https://www.hl7.org/fhir/search.html#modifiers

**Comment by vstrateman** [comment]
Hi @floofydoug --
Yes, that can be done as a searchParam... below is an example of how it would work with the client.
Of course, this will only work if the server you're working with supports the modifier!

`app.get('/api/patient', (req, res) => {
  if (req.query.name) {
    client.search({
      resourceType: 'Patient',
      searchParams: {
        'name:contains': req.query.name
      }
    }).then((response) => {
      const patients = response.entry ? response.entry.map((obj) => {
        return {
          id: obj.resource.id,
          name: `${obj.resource.name[0].given} ${obj.resource.name[0].family}`,
          gender: obj.resource.gender,
          birthDate: obj.resource.birthDate
        }
      }) : [];

      res.status(200).json(patients);
    });
  } else {
    res.status(200).json([]);
  }
});`
