### ISSUE TITLE
Cannot import CapabilityTool

### ISSUE THREAD

**Issue by WesleyKapow** [Vermonster/fhir-kit-client#156]
Not sure where things are going wrong. Trying to import this in typescript and I get `undefined`.

```ts
import Client, { CapabilityTool } from "fhir-kit-client";
console.log(CapabilityTool); // undefined
```

**Comment by bkaney** [comment]
Yea, we need to document this better, or export it better. You have to do this presently:
```javascript
import { CapabilityTool } from 'fhir-kit-client/lib/capability-tool'
```

I think I will add an enhancement task to export this (and a few other) through main.

**Comment by bkaney** [comment]
This is now in 1.8.0
