### ISSUE TITLE
Update to final 4.3.0 (non-snapshot) release.

### ISSUE THREAD

**Issue by preston** [Vermonster/fhir-kit-client#178]
## Expected Behavior

Importing the 'fhir/r4' types would represent the 4.3.0 FHIR 4B release.

## Actual Behavior

It appears the types are generated from the earlier "4.3.0-snapshot1" release.

**Comment by bkaney** [comment]
@preston - yes you are correct. However, this is actually not related to this project by the types at DT (https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/fhir). 

I will work on a PR there and could add you as a reviewer if you are interested.

**Comment by preston** [comment]
@bkaney Sure...

Probably a separate issue/PR, but because of ONC we are also needing to differentiate specific releases, e.g. "4.3.0" or "4.0.1" instead of just "r4". I would propose using the full FHIR release version number in the DT paths instead: "fhir/r4.3.0" and "fhir/r4.0.1", respectively.

**Comment by preston** [comment]
In an ideal world that would be great, but I think there will be many real-world developers (such as our own target audience) that need to target a specific patch release number that might not be current but are required to use. Legislative, compliance, certification/testing programs, FHIR server compatibility, EHR release cycles, local policy, dependency issues etc.

I think it's best for the customer to use the specific version label from the publication history: http://hl7.org/fhir/directory.html

Let me know if this is something we can help with. I know I'm curious how y'all are building this package. In the future we will be needing to experiment with preview/draft releases as well for testing beta FHIR servers releases.

**Comment by bkaney** [comment]
Maybe we move this to Zulip for broader thoughts?

My thinking on DT was to just support the latest major versions to cover most cases. The MS Codegen could be used to generate locally if you really need for dot-releases. My concern with loading all versions in one DT library is size and performance (in your editor / IDE)... but perhaps this isn't a big deal?

Other options include:
* deprecating DT and make a npm package; 
* create @types/fhir4 (with namespaces for related versions, e.g. 4.0.0, 4.0.1, and 4.3.0, etc., so `fhir.4_3_0.Patient` or something). The same for @types/fhir3 and @types/fhir5 etc.

**Comment by preston** [comment]
(will take discussion thread over to https://chat.fhir.org/#narrow/stream/179169-javascript/topic/Publish.20new.20version.20of.20DT.20.40types.2Ffhir )

**Comment by preston** [comment]
@bkaney Hey just checking in on this. I ran the latest version of fhir-codegen yesterday and was able to generate separate .ts files for 4.0.1 and 4.3.0. IDE performance is definitely a big deal, as that is one of the biggest issues I've had using a single .ts file directly from fhir-codegen. I like the namespace idea: seems clean, easy to use, and should keep IDE impact to a minimum.
