### ISSUE TITLE
Browser compatibility issue

### ISSUE THREAD

**Issue by harshita-gupta** [Vermonster/fhir-kit-client#66]
I'm using the fhir-kit-client library to read FHIR data from a react app in-browser. Using webpack to bundle the npm installation of fhir-kit-client into my bundle.js file. Since this runs in-browser, the URLSearchParams API is already present (provided by browser). Therefore, the line at the top of fhir-kit-client/lib/client.js, `const { URLSearchParams } = require('url');`, is overriding the provided URLSearchParams and resulting in the error 'client.js:531 Uncaught TypeError: URLSearchParams is not a constructor`. 

## Expected Behavior
I shouldn't see any errors in my browser console when I use client.search

## Actual Behavior
I get 
``client.js:531 Uncaught TypeError: URLSearchParams is not a constructor``

**Comment by harshita-gupta** [comment]
Thanks very much, @bkaney! Any idea when that might be released, so I can plan development accordingly?

**Comment by bkaney** [comment]
@harshita-gupta can you try out this branch to see if it works for you: https://github.com/Vermonster/fhir-kit-client/pull/67

**Comment by harshita-gupta** [comment]
@bkaney This works great, thanks! Let me know when it's pushed to npm so that I can update my package.json.

**Comment by bkaney** [comment]
See release 0.4.2, up on npmjs now.
