### ISSUE TITLE
Keep alive support

### ISSUE THREAD

**Issue by fungiboletus** [Vermonster/fhir-kit-client#82]
Hei,

I'm using your library and I'm quite happy with it so far. However I noticed that my nodejs application was surprisingly slow compared to what I should expect from my FHIR service. After some investigation, you use a polyfill to use the `fetch` API, which use `node-fetch`, which does not support keep alive by default (unlike `request` or `axios`). Do you think it should be possible/easy to add support for keep alive, or switch to a faster http client library ?

**Comment by Jammjammjamm** [comment]
We can look into enabling keep-alive by default, but for now, you should be able to use keep alive by manually adding the necessary headers to the client:
```
 const client = new Client({
  baseUrl: 'https://some-fhir-server.com',
  customHeaders: {
    Connection: 'Keep-Alive',
    Keep-Alive: 'timeout=5, max=1000'
  }
}
```

**Comment by Jammjammjamm** [comment]
After thinking about it, I realized that just setting the header was unlikely to solve this problem. Related PR which hopefully addresses this issue: #83.
