### ISSUE TITLE
Add typescript declaration files

### ISSUE THREAD

**Issue by thril** [Vermonster/fhir-kit-client#85]
I have just recently discovered this project, and it's pretty much exactly what I was looking for. It would be super useful to have type checking functionality when using this lib. Can you add typescript support to the roadmap for this project?  Thanks!

**Comment by bkaney** [comment]
Thanks @thril -- Good idea. We are working on a FHIR model library, and I think this would be more appropriate there.

**Comment by khanguslee** [comment]
Any update on this?

**Comment by fungiboletus** [comment]
Meanwhile @yinzara made some definitions in DefinitelyTyped : https://www.npmjs.com/package/@types/fhir-kit-client

**Comment by thril** [comment]
> Meanwhile @yinzara made some definitions in DefinitelyTyped : https://www.npmjs.com/package/@types/fhir-kit-client

I had forgotten that I opened this issue a while back. ^ I've been using this package for a little while. However, it's not perfect, so I have to essentially extend functionality to get the expected return types for api requests (read, update, patch, etc).

```typescript
export interface EhrResourceMap {
  Account: fhir.Account;
  ActivityDefinition: fhir.ActivityDefinition;
  AdverseEvent: fhir.AdverseEvent;
  ...
}

export type EhrResourceType = keyof EhrResourceMap;

export interface EhrOperationError {
  response: {
    status: number;
    data: {
      resourceType: "OperationOutcome";
      issue: fhir.OperationOutcomeIssue[];
    };
  };
  config: {
    method: "create" | "patch" | "read" | "update" | "vread";
    url: string;
    headers?: object;
  };
}

...

function isOperationOutcome<T>(
  response: fhir.OperationOutcome | T
): response is fhir.OperationOutcome {
  return (response as fhir.OperationOutcome).issue !== undefined;
}

function isEhrOperationError<T>(
  value: EhrOperationError | T
): value is EhrOperationError {
  return (
    (value as EhrOperationError)?.response?.data?.resourceType ===
    "OperationOutcome"
  );
}

interface EhrUpdateParams<R extends EhrResourceType> {
  body: EhrResourceMap[R];
  context: Context;
  id: string;
  options?: Options;
  resourceType: R;
}

export async function ehrUpdate<R extends EhrResourceType>({
  context,
  ...updateArgs
}: EhrUpdateParams<R>): Promise<EhrResourceMap[R]> {
  try {
    // `context.api.ehr` is an instance of `FhirClient`
    return (await context.api.ehr.update(updateArgs)) as EhrResourceMap[R];
  } catch (e) {
    const message = e.message || "Update Failed";
    if (isEhrOperationError(e)) {
      handleOperationOutcome(e.response.data, "UPDATE_FAILED", message);
    }
    throw new ApolloError(message, "UPDATE_FAILED");
  }
}
```

And consuming this allows the response to have the appropriate type. In this particular case, an instance of `fhir.Patient`.

```typescript
    const patient = await ehrUpdate({
      body,
      context,
      id: patientId,
      resourceType: "Patient"
    })
```

**Comment by fungiboletus** [comment]
Looks like it also uses @types/fhir which is for FHIR 3 and not FHIR 4.

**Comment by bkaney** [comment]
I am working on a PR to update the @types/fhir so we have a r2, r3, r4 and r5 (using MS codegen project https://github.com/microsoft/fhir-codegen); with the default r4 that can advance as the official spec changes.

Then I think it makes sense to move and maintain fhir-kit-client types here, and come up with a pattern where you can specify which fhir version to use. I would be open to ideas about how to do this, as I would like to see if we can support apps that might have two client instances -- one for R3 and R4 in the same app/runtime...

**Comment by yinzara** [comment]
I love that idea

**Comment by WesleyKapow** [comment]
I see @bkaney's [@types PR](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/53511) has been merged, can this now be closed?

**Comment by bkaney** [comment]
yes!
