### ISSUE TITLE
Support servers that only return status code

### ISSUE THREAD

**Issue by sulkaharo** [Vermonster/fhir-kit-client#91]
## Expected Behavior

When performing CRUD operations on a server that implements the 'Prefer: minimal' behavior for object creation, the operation is reported as having worked in case of HTTP 200 or HTTP 201 response in a manner that makes is possible to validate the operation response.

## Actual Behavior

With current implementation, a response with no body causes Client.create() to return nothing (and no error). In terms of determining operation success, this is not optimal, especially since not even the Location: header that points to the created resource is returned.

## Steps to Reproduce the Problem

  1. Try inserting data to a FHIR server that implements the 'Prefer: minimal' behavior and none of the other CRUD response behaviors, such as http://fhirsandbox.kanta.fi/phr-resourceserver-ui/home
  2. Note in case of a successful insert, HTTP 201 Created is returned, along with Location header that points to the created resource
  3. Note Client.create() returns only the request body data, making it impossible to determine fully what happened

## Discussion

I patched my copy of fhir-kit-client to return the request status code, headers and the request body on non-error state, which enables determining the request results in the described scenario. I can PR these in, but sadly the change is not backward compatible with the current API, so I'm not sure how to proceed. The basic issue is in https://github.com/Vermonster/fhir-kit-client/blob/master/lib/http-client.js#L90 where the request object doesn't return the header and response status codes back to the the user.

**Comment by bkaney** [comment]
Thanks @sulkaharo -- this is in 1.3.0 now
