### ISSUE TITLE
Feature request : POST search API

### ISSUE THREAD

**Issue by fungiboletus** [Vermonster/fhir-kit-client#94]
Hei, first thanks for your work.

We have some use cases where our search queries could be relatively large, and we are a bit unsure whether everything in our stack, including HTTP load balancers or reverse proxies, will always accept very long URLs.

[The FHIR documentation](https://www.hl7.org/fhir/http.html#search) has a paragraph about this problem:

> Because of the way that some user agents and proxies treat GET and POST requests, in addition to the get based search method above, servers that support search SHALL also support a POST based search.

Today, `fhir-kit-client` only do `GET` searches. Could it be possible to also do POST searches ? Perhaps by adding an optional parameter on the `.search` method.

**Comment by bkaney** [comment]
Thanks. We willl look into supporting this shortly, it is a good feature to add.

**Comment by bkaney** [comment]
Thanks @fungiboletus -- this is in 1.3.0 now!

**Comment by fungiboletus** [comment]
Great it's working well !
