### ISSUE TITLE
Don't escape string in search

### ISSUE THREAD

**Issue by JustinJruby** [Vermonster/fhir-kit-client#98]
## Expected Behavior
 tryFhirClient.search({"resourceType":"Communication", searchParams:{subject:'http://patient.ehealth.com/Patient/167'}  }).then( (x)=>{console.log(x)})
searches
http://patient.ehealth.com/trifork-fhir-server/Communication?subject=http://patient.ehealth.sundhed.dk/Patient/167
## Actual Behavior
It escapes the subject
http://patient.ehealth.com/fhir-server/Communication?subject=http%3A%2F%2Fpatient.ehealth.com%2FPatient%2F16

**Comment by bkaney** [comment]
Hi @JustinJruby -- According to https://www.hl7.org/fhir/search.html#Introduction "...the parameters are a series of name=[value] pairs encoded in the URL...". It is fairly typical to URL encode search parameters. If we are missing something, please feel free to re-open with new information.
